### ISSUE TITLE
Allow hashbang line

### ISSUE THREAD

**Issue by kornelski** [domenic/traceur-runner#1]
Node allows JS files to start with `#!`, e.g.

```
#!/usr/bin/env node --harmony
console.log("I'm JS");
```

``` sh
node test.js
```

> I'm JS

``` sh
traceur-runner test.js
```

> Uncaught exception: [ 'test.js:1:1: Character code \'35\' is not a valid identifier start char',
>   'test.js:1:1: Unexpected token error',
>   'test.js:1:2: Semi-colon expected',
>   'test.js:1:16: Semi-colon expected',
>   'test.js:1:23: Semi-colon expected' ]

**Comment by hojgr** [comment]
That's a tricky one. I tried to solve it but it is not as easy as I tought it would be. 

My first idea was to simply detect a hashbang line and if it is found on the first line of the script, delete first line and save the file with temp name.

The issue is if the executed script does process.exit or ends with unexpected expection - the temp file remains undeleted.

Any idea how to go around this?

**Comment by domenic** [comment]
Maybe it's best fixed upstream in Traceur, as a pre-parsing step when in a special "node" mode.

**Comment by hojgr** [comment]
I haven't looked into traceur's source code. But wouldn't it be easier to fix it in traceur-runner for now?

**Comment by domenic** [comment]
Very unlikely.
